Songs/urls.py
from django.urls import path, re_path
from .views import home  # import the view
from .views import SongListView, SongDetailView, SongUpdateView, SongDeleteView, SongCreateView  # import the class-based views

urlpatterns = [
    # path('', home, name='home'),  # connect the view to a URL
    path('', SongListView.as_view(), name='song_list'),
    path('<int:song_Number>/<slug:slug>', SongDetailView.as_view(), name='song_detail'),
    # re_path(r'^songs/(?P<song_Number>[0-9]+)/(?P<slug>[\w-]+)/$', SongDetailView.as_view(), name='song_detail'),
    path('<int:song_Number>/<slug:slug>/edit', SongUpdateView.as_view(), name='song_update'),
    path('new/', SongCreateView.as_view(), name='song_create'),
    path('<int:song_Number>/<slug:slug>/delete', SongDeleteView.as_view(), name='song_delete'),

]

Songsapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Songs.urls')),
]

Songs/models.py
from django.db import models
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.urls import reverse

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Song.Status.PUBLISHED)


class Song(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    CATEGORY_CHOICES = [
        ('A', 'స్తుతి, ఆరాధన, సిలువ ద్యానం'),
        ('B', 'హెచ్చరిక, దిద్దుబాటు'),
        ('C', 'ప్రార్థన, విజ్ఞాపన, యాచన'),
        ('D', 'లేఖన విలువ '),
        ('E', 'సేవా పిలుపు, సేవా సమర్పణ'),
        ('F', 'ఆధరణ, ప్రోత్సాహము'),
        ('G', 'యవనస్థులు'),
        ('H', 'సోదరీలు'),
        ('I', 'సువార్త సందేశం, సువార్త పిలుపు'),
        ('J', 'ప్రభువు రాకడ, రాకడ సిద్ధపాటు '),
        ('K', 'అనుబంధ కీర్తనలు'),

    ]

    song_Number = models.IntegerField()
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField(max_length=100, unique=True, blank=True, allow_unicode=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT,
                              )
    objects = models.Manager()
    published = PublishedManager()
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default='A')
    tags = TaggableManager()


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('song_detail',
                       args=[self.song_Number, self.slug])

Songs/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from .models import Song

# Create your views here.

from django.http import HttpResponse

def home(request):
    return HttpResponse("Hello, World!")

class SongListView(ListView):
    model = Song
    template_name = 'songs/song_list.html'
    context_object_name = 'songs'
    paginate_by = 50


    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by('slug')
        search_term = self.request.GET.get('search', '')
        if search_term:

            if search_term.isdigit():
                queryset = queryset.filter(
                    Q(song_Number__exact=search_term)
                )
            else:
                queryset = queryset.filter(
                    Q(title__icontains=search_term) |
                    Q(body__icontains=search_term) |
                    Q(slug__icontains=search_term)
                )

            queryset = queryset.filter(
                Q(title__icontains=search_term) |
                Q(song_Number__icontains=search_term) |
                Q(body__icontains=search_term) |
                Q(slug__icontains=search_term)
            )
        return queryset

class SongDetailView(DetailView):
    model = Song
    template_name = 'songs/song_detail.html'
    context_object_name = 'song'

    def get_object(self):
        song_Number = self.kwargs.get("song_Number")
        slug = self.kwargs.get("slug")

        post = get_object_or_404(Song, song_Number=song_Number, slug=slug)
        return post

class SongUpdateView(UpdateView):
    model = Song
    fields = '__all__'
    template_name = 'songs/song_update.html'

class SongDeleteView(DeleteView):
    model = Song
    template_name = 'songs/song_delete.html'
    success_url = '/songs/'

class SongCreateView(CreateView):
    model = Song
    fields = '__all__'
    template_name = 'songs/song_create.html'
    success_url = '/songs/'

templates/songs/base.html
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
<head>
    <style>

        .navbar-custom {
    background-color: #007bff; /* Assuming this is the color you want for the top bar */
    color: #ffffff; /* This is for the text color */
  }
  .bg-red {
    background-color: #ff0000; /* This is the red background color used in your example */
  }
  .search-container {
    position: relative; /* Needed to position the search form absolutely within it */
  }
  .search-form {
    position: absolute;
    right: 1rem; /* Adjust as necessary */
    top: 50%;
    transform: translateY(-50%); /* Center vertically */
  }
  .search-input {
    border-radius: 20px; /* Rounded borders on the input */
  }
  .search-button {
    border-radius: 20px; /* Consistent rounded borders on the button */
    border: 0; /* Remove default border */
    box-shadow: none; /* Remove default box-shadow if any */
  }

    .custom-list-header {
        color: white;
    }

  .custom-header {
    background-color: #ff0000; /* Adjust the color to match your need */
    color: white;
    padding: 10px;
    font-weight: bold;
  }
  .custom-link-group-item {
    border: none; /* Removes the default border */
    border-bottom: 1px solid #ddd; /* Adds a border to the bottom of each item */
    color: inherit; /* Ensures the text color is not changed by the link */
    text-decoration: none; /* No underline for the link */
  }
  .custom-link-group-item:hover {
    background-color: #f8f9fa; /* Slight change on hover for feedback */
  }
  .custom-badge {
    background-color: #ff0000; /* Same red as the header for consistency */
  }
  /* Other custom styles */
</style>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block Title %}Songs Book{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        {% block Content %}

        {% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/songs/song_create.html
{% extends 'songs/base.html' %}
{% load widget_tweaks %}

{% block Content %}
	<div class="container my-5">
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
                <div class="col-md-6 mb-3"> <!-- Adjust the column sizes as needed -->
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {% render_field field class="form-control" placeholder=field.label %}

                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}

                    {% if field.errors %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger mt-2">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

templates/songs/song_delete.html
{% extends 'songs/base.html' %}

{% block Title %}

{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            Confirm Delete
        </div>
        <div class="card-body">
            <h5 class="card-title">Are you sure you want to delete this song?</h5>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Yes, delete</button>
                <a href="{% url 'song_list' %}" class="btn btn-secondary">No, take me back</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/songs/song_detail.html
{% extends 'songs/base.html' %}

{% block Title %}
    {{ song.title }}
{% endblock %}

{% block Content %}

<div class="container mt-5">
    <h1 class="display-6">{{ song.title }}</h1> <!-- Even smaller title with display-6 -->
    <hr class="my-4">
    <article class="mb-5">
        <!-- Use p instead of div for text, with text-break to ensure wrapping -->
        <p class="lead bg-light p-3 rounded" style="white-space: pre-wrap; font-size: 0.9rem;"> <!-- Adjust font size as needed -->
            {{ song.body }}
        </p>
    </article>
    <!-- Additional song details here -->
{#    <section>#}
{#        <h2 class="h6">Details</h2>#}
{#        <p><strong>Song Number:</strong> {{ song.number }}</p>#}
{#        <p><strong>Status:</strong> {{ song.get_status_display }}</p>#}
{#        <p><strong>Tags:</strong> {{ song.tags }}</p>#}
{#    </section>#}
</div>

{% endblock %}

templates/songs/song_list.html
{% extends 'songs/base.html' %}

{% block Title %}
 SONGS BOOK
{% endblock %}

{% block Content %}

    <nav class="navbar navbar-custom navbar-expand-lg">
  <div class="container-fluid search-container">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="#">SONGS BOOK</a>
    <!-- Search form -->
    <form class="search-form d-flex" method="get" action="{% url 'song_list' %}">
      <input class="form-control me-2 search-input" type="text" name="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light search-button" type="submit">Search</button>
    </form>
  </div>
</nav>




    <ul class="list-group">
    <li class="list-group-item custom-link-group-item d-flex justify-content-between align-items-center bg-danger custom-color" style="position: sticky ; top:0; z-index: 2">
        <div class="ms-2 me-auto custom-list-header">
            <div class="fw-bold">పాట పేరు</div>
        </div>
        <span class="badge custom-color " >సంఖ్య</span>

    </li>
    {% for song in songs %}
        <a href="{{ song.get_absolute_url }}" class="list-group-item custom-link-group-item d-flex justify-content-between align-items-center">
            <div class="ms-2 me-auto">
                <div class="fw-bold">{{ song.title }}</div>
                 </div>
            <span class="badge bg-primary "  >{{ song.song_Number }}</span>

        </a>
    {% endfor %}
    </ul>

{% endblock %}

templates/songs/song_update.html
{% extends 'songs/base.html' %}
{% load widget_tweaks %}


{% block Content %}



<div class="container my-5">
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
                <div class="col-md-6 mb-3"> <!-- Adjust the column sizes as needed -->
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {% render_field field class="form-control" placeholder=field.label %}

                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}

                    {% if field.errors %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger mt-2">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>

{% endblock %}